disableKinds = ['taxonomy', 'term']
baseURL = 'https://dmaivel.com/'
languageCode = 'en-us'
title = 'dmaivel'
[markup]
  [markup.highlight]
    style = "vs"
    noClasses=false
[markup.goldmark.renderer]
  unsafe = true
[markup.goldmark.extensions.passthrough]
  enable = true
[markup.goldmark.extensions.passthrough.delimiters]
  block = [['\[', '\]'], ['$$', '$$']]
  inline = [['\(', '\)'], ['$', '$']]
[markup.goldmark.parser]
  autoHeadingID = true
  autoHeadingIDType = "github"
[params]
  favicon = "./favicon.ico"
[permalinks]
  posts = "/:contentbasename/"